# Default port is 12001
server:
  port: 12001

spring:
  profiles:
    active:
      default

eureka:
  client:
    registerWithEureka: true # 유레카 서비스에 자신 등록
    fetchRegistry: false # 레지스트리 정보 로컬 캐싱
  server:
    waitTimeInMsWhenSyncEmpty: 5 # 서버가 요청을 받기 전 대기할 초기 시간
  serviceUrl:
    defaultZone: http://localhost:12001
  
---

spring:
  profiles:
    active:
      dev

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serviceUrl:
    defaultZone: http://dev.avocadostudio:12002