
##### DEFAULT #####

spring:
  profiles: default

server:
  port: 12001

eureka:
  client:
    registerWithEureka: false # 유레카 서비스에 자신 등록
    fetchRegistry: false # 레지스트리 정보 로컬 캐싱
  server:
    waitTimeInMsWhenSyncEmpty: 5 # 서버가 요청을 받기 전 대기할 초기 시간
  serviceUrl:
    defaultZone: http://localhost:12001
  
---

##### DEV #####

spring:
  profiles: dev

server:
  port: 8080

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serviceUrl:
    defaultZone: http://localhost:8080